version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: viiotest
    ports:
      - 5432:5432

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - db

  # client:
  #   build: ./client
  #   volumes:
  #     - ./client:/usr/src/app
  #   ports:
  #     - 3000:3000